services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - flask_app
    environment:
      API_BACKEND: flask_app

  flask_app:
    build: ./flask_app
    ports:
      - "5000:5000"
    environment:
      - TEST_MODE=${TEST_MODE}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SECRET_KEY=${SECRET_KEY}

