apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: psychometry-app-secrets
  labels:
    app.kubernetes.io/name: {{ include "chart-psychometric.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
